### ISSUE TITLE
Thinking of doing an R training course based around "R for Data Science"

### ISSUE THREAD

**Issue by michaelbarton** [hbctraining/Intro-to-R#1]
I'm thinking about training my collegues at the JGI about using R based on the ["R for Data Science"](http://r4ds.had.co.nz/) book. Since you already have a course based around introduction to R, is there a good way to contribute or collaborate?

**Comment by rkhetani** [comment]
Michael, if you want to use our materials, you are welcome to fork any of the repos and use them as per our license (listed in the readme as well as our lessons). 

We are also happy to collaborate to improve or develop more advanced materials; please let me know what you have in mind and if you want to set up a time to chat.

**Comment by michaelbarton** [comment]
Thanks for following up. We're still very early in planning but hopeful will run an ongoing R training at the JGI at some point.
