### ISSUE TITLE
Two small possible errors in outputs displayed.

### ISSUE THREAD

**Issue by samuel-marsh** [hbctraining/Intro-to-R#2]
I think I've spotted two minor errors in the outputs list the tidyverse lesson.
1.  Output size of tibble at one point
2.  Not resaving tibble effecting output size at another point.
See PDF created from markdown (attached).
[HBC_tidyverse lesson.pdf](https://github.com/hbctraining/Intro-to-R/files/1968181/HBC_tidyverse.lesson.pdf)

If error is on my end, my apologies and please let me know what I've done incorrectly vs. the website.

Thanks,
Sam

**Comment by rkhetani** [comment]
Thanks for your input Sam!! We'll check + make the necessary changes, and let you know how it goes.

Best,
Radhika

**Comment by rkhetani** [comment]
They have been fixed,thanks again @samuel-marsh!
